#!/bin/sh

# Copyright 2006-2007 Freescale Semiconductor, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

if [ "$1" = "start" -o "$1" = "restart" ]
then
    echo "Mounting /proc and /sys "
    mount -n -t proc proc /proc
    mount -n -t sysfs sys /sys
fi
