#!/bin/sh
i=0
PROG_NAME='avl-monitor'
LOG="/var/log/"`echo -n $0|sed 's/.*\///'`".processlog"
LAST_MSG=''
while true
do
	i=`expr $i + 1`
	if [ -e "/home/root/log.enabled" ] ; then
		uptime > $LOG
		date >> $LOG
		echo "starts: $i" >> $LOG
		echo "lastmsg: $LAST_MSG" >> $LOG
	fi
	avl-monitor
	LAST_MSG="$PROG_NAME exited with code $?, restarting..."
	sleep 1
done
exit 0
