#!/bin/sh
echo > /dev/watchdog
logger -s "===== setup-firewall ====="

mount|grep "/dev/root on / type nfs" 2>/dev/null
if [ 0 = "$?" ];then
	exit 0
fi
iptables -F

iptables -P INPUT DROP
iptables -P FORWARD DROP

iptables -P OUTPUT ACCEPT
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -i lo -j ACCEPT
iptables -I INPUT -i ra0 -p udp --dport 67:68 --sport 67:68 -j ACCEPT
iptables -I INPUT -i eth0 -p udp --dport 67:68 --sport 67:68 -j ACCEPT
iptables -I INPUT -i eth0 -p tcp --dport 22 -j ACCEPT
iptables -I INPUT -i eth0 -p tcp --dport 80 -j ACCEPT
iptables -I INPUT -i ra0 -p tcp --dport 80 -j ACCEPT
iptables -I INPUT -i ppp0 -p udp --dport 41414 -j ACCEPT
iptables -t nat -F
iptables -t nat -A POSTROUTING -o ppp0 -j MASQUERADE
iptables -t nat -A POSTROUTING -o apcli0 -j MASQUERADE
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
iptables -t nat -A POSTROUTING -o ra0 -j MASQUERADE
iptables -A FORWARD -i ppp0 -o eth0 -j DROP
iptables -A FORWARD -i eth0 -o ppp0 -j DROP
iptables -A FORWARD -i ppp0 -o ra0  -j DROP
iptables -A FORWARD -i ra0 -o ppp0 -j DROP
iptables -A FORWARD -i ra0 -o eth0 -j DROP
iptables -A FORWARD -i eth0 -o ra0 -j DROP
iptables -A FORWARD -i ra0 -o apcli0 -j ACCEPT
iptables -A FORWARD -i apcli0 -o ra0 -j ACCEPT
iptables -A FORWARD -i eth0 -o apcli0 -j ACCEPT
iptables -A FORWARD -i apcli0 -o eth0 -j ACCEPT
iptables -A INPUT -i eth0 -p tcp -m tcp --dport 443 -j ACCEPT
iptables -A INPUT -i ra0 -p tcp -m tcp --dport 443 -j ACCEPT

echo '1' > /proc/sys/net/ipv4/ip_forward
exit 0
