#!/bin/sh
PATH=$PATH:/sbin:/bin

if [ ! -x /sbin/udevd ]
then
		exit 0
fi

#set the speed here since changing the speed after the Gemalto modem comes up causes the ports to disappear.
echo 360000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed

case "$1" in
		start)
			echo > /dev/watchdog
			logger -s "===== udev - start ====="
			echo "" > /proc/sys/kernel/hotplug

			mount -n -o mode=0755 -t tmpfs tmpfs /dev

				# Create static device nodes in /dev
			mknod /dev/console c 5 1
			mknod /dev/null c 1 3
			. /etc/rc.d/init.d/redstone-static-dev

			echo "Starting the hotplug events dispatcher udevd"
			udevd --daemon

			echo "Synthesizing initial hotplug events"
			udevtrigger
			udevsettle --timeout=300

			mkdir /dev/pts
			mount -n -t devpts devpts /dev/pts

			mkdir /dev/shm
			
			mkdir /tmp/ramdisk
			chmod 777 /tmp/ramdisk
			mount -t tmpfs -o size=128k myramdisk /tmp/ramdisk
			
			#	Turn off the leds - this should be the earliest time that we can do this since i2c just came up.
			#Turn off the red leds.
			i2cset -y	0 0x20	0x03 0xFF
			#Turn off the green leds.
			i2cset -y	0 0x20	0x02 0xFF
			#Turn the POWER LED orange
			echo UT > /dev/set-gpio
			;;
		stop)
			#Turn off the red leds.
			i2cset -y	0 0x20	0x03 0xFF
			#Turn off the green leds.
			i2cset -y	0 0x20	0x02 0xFF
			#Turn the POWER LED orange
			echo UT > /dev/set-gpio
			;;
		reload)
			udevcontrol --reload_rules
			;;
		*)
			echo "Usage: /etc/rc.d/init.d/udev {start|stop|reload}"
			echo
			exit 1
			;;
esac

exit 0
