# LCM configuration settings for SuperAdmin and Installer
Cellular carrier
Cellular Password
Cellular UserName
ComPorts Com1Baud
ComPorts Com1Dest
ComPorts Com1Enable
ComPorts Com1Port
ComPorts Com2Baud
ComPorts Com2Dest
ComPorts Com2Enable
ComPorts Com2Port
feature can-dodge-seatbelt-monitor
feature can-ford-seatbelt-monitor
feature can-gm-seatbelt-monitor
feature gps-socket-server
feature i2c-gpio-monitor
feature packetizer
feature packetizer-calamps
feature packetizer-dash
feature PROC_Seatbelt
gps-socket-server listen_server_port
i2c-gpio-monitor input1
i2c-gpio-monitor input2
i2c-gpio-monitor input3
i2c-gpio-monitor input4
modbus PGN1
modbus PGN2
modbus PGN3
modbus q_delay_seconds
modbus SPN1
modbus SPN2
modbus SPN3
MSGPriority acceleration
MSGPriority accept_accel_resumed
MSGPriority calamp_user_msg
MSGPriority check_in
MSGPriority check_out
MSGPriority crit_batt
MSGPriority driver_status
MSGPriority engine_off
MSGPriority engine_on
MSGPriority engine_param_exceed
MSGPriority engine_param_normal
MSGPriority engine_period_report
MSGPriority engine_trouble_code
MSGPriority fall_detected
MSGPriority fuel_log
MSGPriority gpsfix_invalid
MSGPriority hard_brake
MSGPriority heartbeat
MSGPriority help
MSGPriority ignition_off
MSGPriority ignition_on
MSGPriority j1939
MSGPriority j1939_fault
MSGPriority j1939_status2
MSGPriority low_batt
MSGPriority mp_accept_deccel_resumed
MSGPriority not_check_in
MSGPriority odometer_update
MSGPriority ok
MSGPriority other
MSGPriority ping
MSGPriority power_off
MSGPriority power_on
MSGPriority scheduled_message
MSGPriority sensor
MSGPriority sos
MSGPriority speed_acceptable
MSGPriority speed_exceeded
MSGPriority start_condition
MSGPriority stop_condition
MSGPriority text
packetizer-calamps host
packetizer-calamps m_max_backlog
packetizer-calamps port
packetizer-calamps UseCompression
packetizer-dash host
packetizer-dash port
packetizer host
packetizer port
PositionUpdate Distance
PositionUpdate Heading
PositionUpdate IncreaseStoppedReportTime
PositionUpdate MinSendTime
PositionUpdate Pinning
PositionUpdate ReportStopStart
PositionUpdate ReportWhenStopped
PositionUpdate StopTime
PositionUpdate StopVel
PositionUpdate Time
RedStone DisableSleep
RedStone EnableGPSReboot
RedStone IgnitionSource
RedStone KeepAwakeMinutes
RedStone SpeedSource
SER_GPS sendGPS
trip-monitor StartupDistance
