#!/bin/sh
export DONT_TOUCH_RESOLV_CONF=1
[ -z "$1" ] && echo "Error: should be called from udhcpc" && exit 1

[ -n "$broadcast" ] && BROADCAST="broadcast $broadcast"
[ -n "$subnet" ] && NETMASK="netmask $subnet"

case "$1" in
	deconfig)
		/sbin/ifconfig $interface 0.0.0.0
		;;
	renew|bound)
		/sbin/ifconfig $interface $ip $BROADCAST $NETMASK
		;;
esac

exit 0

