obj-$(CONFIG_REDSTONE_DRIVERS) +=\
	redstone.o

obj-$(CONFIG_REDSTONE_SET_GPIO)	+=\
	set-gpio.o

obj-$(CONFIG_REDSTONE_BATTERY_VOLTAGE)	+=\
	battery.o

obj-$(CONFIG_REDSTONE_HID_VOLTAGE)	+=\
	hid.o

obj-$(CONFIG_REDSTONE_WIFITRAFFIC)	+=\
	wifitraffic.o

obj-$(CONFIG_REDSTONE_BUZZER_GPIO) +=\
	buzzer.o

obj-$(CONFIG_TRULINK_ETHERNET_PHY_SUSPEND) +=\
	pm.o

obj-$(CONFIG_REDSTONE_I2C_GPIO_EXPANDER_IRQ) +=\
	i2c-expander-irq.o

obj-$(CONFIG_REDSTONE_RESET_BUTTON)	+=\
	reset-button.o

obj-$(CONFIG_TRULINK_IRIDIUM_EMULATOR)	+=\
	iridium-emulator.o

obj-$(CONFIG_REDSTONE_LENS_URGENT_INTERRUPT) +=\
	lens-urgent.o
