#!/bin/sh
db-config set feature packetizer-calamps 1
db-config set packetizer-calamps host 192.168.141.35
db-config set packetizer-calamps ack_type short
db-config set packetizer-calamps port 2610
db-config set packetizer-calamps timeout 20
killall packetizer-calamps
echo "Unit is ready for test - Please drive a test loop."
echo "Log into GFI and look for test loop upon completion."

